USE ParalympicGames;
ALTER TABLE Coach
DROP FOREIGN KEY coach_ibfk_1;

ALTER TABLE Coach
ADD CONSTRAINT ID_Person
FOREIGN KEY (ID_Person) REFERENCES Person(ID_Person) ON DELETE SET NULL;

USE ParalympicGames;
ALTER TABLE Coach
DROP FOREIGN KEY coach_ibfk_2;

ALTER TABLE Coach
ADD CONSTRAINT ID_Team
FOREIGN KEY (ID_Team) REFERENCES Team(ID_Team) ON DELETE SET NULL;

