-- CREATE DATABASE ParalympicGames;
USE ParalympicGames;

CREATE TABLE ADMINISTRATOR (
    ID_ADMIN INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_PERSON INT(5),
    PASSWORD_ADMIN VARCHAR(20),
    USERNAME VARCHAR(20)
);
-- DDL for Table CANTON
CREATE TABLE CANTON (
    ID_CANTON INT(5) PRIMARY KEY AUTO_INCREMENT,
    CANTON_NAME VARCHAR(15),
    ID_PROVINCE INT(5)
);

-- DDL for Table COACH
CREATE TABLE COACH (
    ID_COACH INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_PERSON INT(5),
    ID_TEAM INT(5)
);

-- DDL for Table COACHXCOMPETITOR
CREATE TABLE COACHXCOMPETITOR (
    ID_COACHXCOMPETITOR INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_COACH INT(5),
    ID_COMPETITOR INT(5)
);

-- DDL for Table COMPETITION
CREATE TABLE COMPETITION (
    ID_COMPETITION INT(5) PRIMARY KEY AUTO_INCREMENT,
    COMPETITIONNAME VARCHAR(15),
    COMPETITIONDATE DATE,
    COMPETITIONDESCRIPTION VARCHAR(30),
    ID_COMPETITIONTYPE INT(5)
);

-- DDL for Table COMPETITIONTYPE
CREATE TABLE COMPETITIONTYPE (
    ID_COMPETITIONTYPE INT(5) PRIMARY KEY AUTO_INCREMENT,
    TYPEDESCRIPTION VARCHAR(30)
);

-- DDL for Table COMPETITOR
CREATE TABLE COMPETITOR (
    ID_COMPETITOR INT(5) PRIMARY KEY AUTO_INCREMENT,
    CLASIFICATIONSCORE INT(5),
    ID_PERSON INT(5),
    ID_TEAM INT(5)
);

-- DDL for Table COMPETITORXCOMPETITION
CREATE TABLE COMPETITORXCOMPETITION (
    ID_COMPETITORXCOMPETITION INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_COMPETITOR INT(5),
    ID_COMPETITION INT(5),
    TIMERECORDED INT(10),
    SCORE INT(5),
    POSITIONRECORDED INT(5)
);

-- DDL for Table COMPETITORXDISABILITY
CREATE TABLE COMPETITORXDISABILITY (
    ID_COMPETITORXDISABILITY INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_COMPETITOR INT(5),
    ID_DISABILITY INT(5)
);

-- DDL for Table COUNTRY
CREATE TABLE COUNTRY (
    ID_COUNTRY INT(5) PRIMARY KEY AUTO_INCREMENT,
    COUNTRY_NAME VARCHAR(15),
    ID_PICTURE INT(5)
);

-- DDL for Table COUNTRYXPARALYMPIC
CREATE TABLE COUNTRYXPARALYMPIC (
    ID_COUNTRYXPARALYMPIC INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_PARALYMPIC INT(5),
    ID_COUNTRY INT(5)
);

-- DDL for Table DISABILITY
CREATE TABLE DISABILITY (
    ID_DISABILITY INT(5) PRIMARY KEY AUTO_INCREMENT,
    DISABILITYNAME VARCHAR(20)
);

-- DDL for Table DISTRICT
CREATE TABLE DISTRICT (
    ID_DISTRICT INT(5) PRIMARY KEY AUTO_INCREMENT,
    DISTRICT_NAME VARCHAR(15),
    ID_CANTON INT(5)
);

-- DDL for Table EMAIL
CREATE TABLE EMAIL (
    ID_EMAIL INT(5) PRIMARY KEY AUTO_INCREMENT,
    EMAILADRESS VARCHAR(20),
    ID_PERSON INT(5)
);

-- DDL for Table GENDERTYPE
CREATE TABLE GENDERTYPE (
    ID_GENDERTYPE INT(5) PRIMARY KEY AUTO_INCREMENT,
    GENDERTYPE VARCHAR(2)
);

-- DDL for Table IDENTIFICATIONTYPE
CREATE TABLE IDENTIFICATIONTYPE (
    ID_IDENTIFICATIONTYPE INT(5) PRIMARY KEY AUTO_INCREMENT,
    IDENTIFICATIONTYPE VARCHAR(2)
);

-- DDL for Table MEDAL
CREATE TABLE MEDAL (
    ID_MEDAL INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_MEDALTYPE INT(5)
);

-- DDL for Table MEDALTYPE
CREATE TABLE MEDALTYPE (
    ID_MEDALTYPE INT(5) PRIMARY KEY AUTO_INCREMENT,
    TYPENAME VARCHAR(15) NOT NULL
);

-- DDL for Table MEDALXCOMPETITIONXCOMPETITOR
CREATE TABLE MEDALXCOMPETITIONXCOMPETITOR (
    ID_MEDALXCOMPXCOMP INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_MEDAL INT(5),
    ID_COMPETITORXCOMPETITION INT(5)
);

-- DDL for Table NATIONALITY
CREATE TABLE NATIONALITY (
    ID_NATIONALITY INT(5) PRIMARY KEY AUTO_INCREMENT,
    NATIONALITYNAME VARCHAR(20)
);

-- DDL for Table NATIONALITYXPERSON
CREATE TABLE NATIONALITYXPERSON (
    ID_NATIONALITYXPERSON INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_NATIONALITY INT(5),
    ID_PERSON INT(5)
);

-- DDL for Table PARALYMPIC
CREATE TABLE PARALYMPIC (
    ID_PARALYMPIC INT(5) PRIMARY KEY AUTO_INCREMENT,
    PARALYMPICS_YEAR INT(4),
    ID_COUNTRY INT(5)
);

-- DDL for Table PARALYMPICXCOMPETITION
CREATE TABLE PARALYMPICXCOMPETITION (
    ID_PARALYMPICXCOMPETITION INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_PARALYMPIC INT(5),
    ID_COMPETITION INT(5)
);

-- DDL for Table PERSON
CREATE TABLE PERSON (
    ID_PERSON INT(5) PRIMARY KEY AUTO_INCREMENT,
    IDENTIFICATIONNUMBER INT(5),
    FIRSTNAME VARCHAR(15),
    SECONDNAME VARCHAR(15),
    FIRSTLASTNAME VARCHAR(15),
    SECONDLASTNAME VARCHAR(15),
    BIRTHDATE DATE,
    ID_PICTURE INT(5),
    ID_COUNTRY INT(5),
    ID_GENDERTYPE INT(5),
    ID_IDENTIFICATIONTYPE INT(5),
    AGE INT(2)
);

-- DDL for Table PERSONXPHONE
CREATE TABLE PERSONXPHONE (
    ID_PHONEXPERSON INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_PERSON INT(5),
    ID_PHONE INT(5)
);

-- DDL for Table PHONE
CREATE TABLE PHONE (
    ID_PHONE INT(5) PRIMARY KEY AUTO_INCREMENT,
    PHONENUMBER BIGINT(10),
    ID_PHONETYPE INT(5)
);

-- DDL for Table PHONETYPE
CREATE TABLE PHONETYPE (
    ID_PHONETYPE INT(5) PRIMARY KEY AUTO_INCREMENT,
    PHONETYPE VARCHAR(15)
);

-- DDL for Table PICTURE
CREATE TABLE PICTURE (
    ID_PICTURE INT(5) PRIMARY KEY AUTO_INCREMENT,
    IMAGE BLOB
);












-- Ref Constraints for Table ADMINISTRATOR
ALTER TABLE `ADMINISTRATOR`
  ADD FOREIGN KEY (`ID_PERSON`)
    REFERENCES `PERSON` (`ID_PERSON`);

CREATE TABLE Province (
	ID_Province INT(5) PRIMARY KEY AUTO_INCREMENT,
    Province_Name VARCHAR(50),
    ID_Country INT(5),
    FOREIGN KEY (ID_Country) REFERENCES Country(Id_Country));
    
    
-- Ref Constraints for Table CANTON
ALTER TABLE `CANTON`
  ADD FOREIGN KEY (`ID_PROVINCE`)
    REFERENCES `PROVINCE` (`ID_PROVINCE`);

-- Ref Constraints for Table COACH
ALTER TABLE `COACH`
  ADD FOREIGN KEY (`ID_PERSON`)
    REFERENCES `PERSON` (`ID_PERSON`);
    
  CREATE TABLE Team (
	ID_Team INT(5) PRIMARY KEY AUTO_INCREMENT,
    TeamName VARCHAR(50),
    QuantityMembers INT(5)
);

ALTER TABLE `COACH`
  ADD FOREIGN KEY (`ID_TEAM`)
    REFERENCES `TEAM` (`ID_TEAM`);

-- Ref Constraints for Table COACHXCOMPETITOR
ALTER TABLE `COACHXCOMPETITOR`
  ADD FOREIGN KEY (`ID_COACH`)
    REFERENCES `COACH` (`ID_COACH`);

ALTER TABLE `COACHXCOMPETITOR`
  ADD FOREIGN KEY (`ID_COMPETITOR`)
    REFERENCES `COMPETITOR` (`ID_COMPETITOR`);

-- Ref Constraints for Table COMPETITION
ALTER TABLE `COMPETITION`
  ADD FOREIGN KEY (`ID_COMPETITIONTYPE`)
    REFERENCES `COMPETITIONTYPE` (`ID_COMPETITIONTYPE`);

-- Ref Constraints for Table COMPETITOR
ALTER TABLE `COMPETITOR`
  ADD FOREIGN KEY (`ID_PERSON`)
    REFERENCES `PERSON` (`ID_PERSON`);

ALTER TABLE `COMPETITOR`
  ADD FOREIGN KEY (`ID_TEAM`)
    REFERENCES `TEAM` (`ID_TEAM`);

-- Ref Constraints for Table COMPETITORXCOMPETITION
ALTER TABLE `COMPETITORXCOMPETITION`
  ADD FOREIGN KEY (`ID_COMPETITION`)
    REFERENCES `COMPETITION` (`ID_COMPETITION`);
    
CREATE TABLE Score (
	ID_Score INT(5) PRIMARY KEY AUTO_INCREMENT,
    Score INT(5),
    ID_Competition INT(5),
    FOREIGN KEY (ID_Competition) REFERENCES Competition(Id_Competition));
